version: '3.8'

services:
networks:
  app-network:
    driver: bridge

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:5000/api  # Usa el nombre del servicio backend
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    command: --auth

volumes:
  mongodb_data: